### ISSUE TITLE
flat-manager dependencies are outdated

### ISSUE THREAD

**Issue by RytoEX** [flatpak/flatpak-github-actions#130]
While https://github.com/flatpak/flatpak-github-actions/commit/8326776c192b08950984ee5474f0ef035ae090dd updated flatpak-builder's dependencies (for example, updating `@actions/core` from 1.2.6 to 1.10.0), it seems that the dependencies of flat-manager were not updated. I asked @GeorgesStavracas about this and he suggested that this might have been an oversight and asked me to open a GitHub Issue for follow-up and tracking.

**Comment by bilelmoussaoui** [comment]
The important file to look at is the yarn.lock, which already uses 1.10.0, if you want to bump the versions on the package.json file, please send a patch
