### ISSUE TITLE
Action suddenly started to fail

### ISSUE THREAD

**Issue by a1batross** [flatpak/flatpak-github-actions#136]
I use flatpak-github-actions in my project. My workflow file: https://github.com/FWGS/xash3d-fwgs/blob/master/.github/workflows/c-cpp.yml#L67-L91

The log file shows few lines before complete fail:
```
(flatpak-builder:683): GLib-CRITICAL **: 09:27:17.094: g_propagate_error: assertion 'src != NULL' failed
Error: module bundle-setup: Protocol "data" not supported or disabled in libcurl
Error: Build failed: Error: The process '/usr/bin/xvfb-run' failed with exit code 1
```

The action log file is https://github.com/FWGS/xash3d-fwgs/actions/runs/4971642736/jobs/8896307408

I noticed this yesterday, but this probably has been broken for a week now. I also tried to upgrade from v5 to v6.1, and it didn't help.

If there are any steps should be done to debug it, I would gladly help.

**Comment by RossComputerGuy** [comment]
Similar thing for me, happened after I tried integrating cross compiling.
```
Dependency Sdk: org.freedesktop.Sdk 22.08
Installing org.freedesktop.Sdk/x64/22.08 from flathub
error: Nothing matches org.freedesktop.Sdk in remote flathub
Error installing deps: running `flatpak --system install -y --noninteractive flathub org.freedesktop.Sdk/x64/22.08`: Child process exited with code 1
Error: Build failed: Error: The process '/usr/bin/xvfb-run' failed with exit code 1
``
https://github.com/ExpidusOS/file-manager/actions/runs/5365636180/workflow#L124-L183

**Comment by a1batross** [comment]
For me, getting rid of inlined data in file URL helped. https://github.com/FWGS/xash3d-fwgs/commit/ef4bc2acf20ac8f5b12f821f1b31b13797aacad6

**Comment by RossComputerGuy** [comment]
I don't have any sources like that, only 1 source that if I were to remove it would make my app not build. https://github.com/ExpidusOS/file-manager/blob/master/data/com.expidusos.file_manager.yml

**Comment by a1batross** [comment]
>error: Nothing matches org.freedesktop.Sdk in remote flathub

I don't like this line. It seems it can't fetch Sdk package for some reason. But because flatpak isn't really verbose enough, who can even guess why?

**Comment by bilelmoussaoui** [comment]
Is this still happening?

**Comment by a1batross** [comment]
Never encountered this bug since I deleted inlined data URI.

As for @RossComputerGuy, I don't know. But it seems fine on their repositories now. I think it can be closed?..

**Comment by RossComputerGuy** [comment]
I did a revert for a change, I don't remember what the change was that caused the issue in the first place though.

**Comment by bilelmoussaoui** [comment]
Let us close it then, feel free to re-open if something weird happens again

**Comment by kaii-lb** [comment]
Happening again, i changed nothing but a version bump from latest on https://github.com/kaii-lb/overskride/ and it stopped compiling.

**Comment by alyssadev** [comment]
fwiw @kaii-lb I tried building the previous commit before you bumped the version and it failed https://github.com/alyssadev/overskride/actions/runs/8405726261 I'm investigating if there's a path not being included in the flatpak build maybe

**Comment by kaii-lb** [comment]
interesting thing is i removed the appdata.xml and it built. im gonna check it out today but a better error message woulda been realllly helpful
