### ISSUE TITLE
Can I choose the name of the artifact to upload the flatpak as?

### ISSUE THREAD

**Issue by rohitpid** [flatpak/flatpak-github-actions#199]
I don't think there is an option to set the name of the artifact to upload.

**Comment by bilelmoussaoui** [comment]
see the bundle input https://github.com/flatpak/flatpak-github-actions?tab=readme-ov-file#inputs

**Comment by rohitpid** [comment]
I should have been more specific. If you are talking about bundle: then it's not quite right. It appends the arch like x86_64 to the name given there. The user doesn't have full control of the name.
