### ISSUE TITLE
gnome-47 runtime is not yet available

### ISSUE THREAD

**Issue by joshua-stone** [flatpak/flatpak-github-actions#201]
It appears that the `gnome-47`  runtime [was merged a few days](https://github.com/flatpak/flatpak-github-actions/pull/200), but I don't see it showing up as a [valid tag](https://hub.docker.com/r/bilelmoussaoui/flatpak-github-actions/tags) yet:

```
$ skopeo list-tags docker://bilelmoussaoui/flatpak-github-actions
{
    "Repository": "docker.io/bilelmoussaoui/flatpak-github-actions",
    "Tags": [
        "elementary-juno",
        "freedesktop-20.08",
        "freedesktop-21.08",
        "freedesktop-22.08",
        "freedesktop-23.08",
        "freedesktop-24.08",
        "gnome-3.38",
        "gnome-40",
        "gnome-41",
        "gnome-42",
        "gnome-43",
        "gnome-44",
        "gnome-45",
        "gnome-46",
        "gnome-nightly",
        "kde-5.15",
        "kde-5.15-21.08",
        "kde-5.15-22.08",
        "kde-5.15-23.08",
        "kde-6.2",
        "kde-6.3",
        "kde-6.4",
        "kde-6.5",
        "kde-6.6",
        "kde-6.7",
        "latest"
    ]
}
```

**Comment by joshua-stone** [comment]
It appears that `gnome-47` is now available.

```
$ skopeo list-tags docker://bilelmoussaoui/flatpak-github-actions
{
    "Repository": "docker.io/bilelmoussaoui/flatpak-github-actions",
    "Tags": [
        "elementary-juno",
        "freedesktop-20.08",
        "freedesktop-21.08",
        "freedesktop-22.08",
        "freedesktop-23.08",
        "freedesktop-24.08",
        "gnome-3.38",
        "gnome-40",
        "gnome-41",
        "gnome-42",
        "gnome-43",
        "gnome-44",
        "gnome-45",
        "gnome-46",
        "gnome-47",
        "gnome-nightly",
        "kde-5.15",
        "kde-5.15-21.08",
        "kde-5.15-22.08",
        "kde-5.15-23.08",
        "kde-6.2",
        "kde-6.3",
        "kde-6.4",
        "kde-6.5",
        "kde-6.6",
        "kde-6.7",
        "latest"
    ]
}
```

Thank you!

**Comment by bilelmoussaoui** [comment]
> It appears that `gnome-47` is now available.
> 
> ```
> $ skopeo list-tags docker://bilelmoussaoui/flatpak-github-actions
> {
>     "Repository": "docker.io/bilelmoussaoui/flatpak-github-actions",
>     "Tags": [
>         "elementary-juno",
>         "freedesktop-20.08",
>         "freedesktop-21.08",
>         "freedesktop-22.08",
>         "freedesktop-23.08",
>         "freedesktop-24.08",
>         "gnome-3.38",
>         "gnome-40",
>         "gnome-41",
>         "gnome-42",
>         "gnome-43",
>         "gnome-44",
>         "gnome-45",
>         "gnome-46",
>         "gnome-47",
>         "gnome-nightly",
>         "kde-5.15",
>         "kde-5.15-21.08",
>         "kde-5.15-22.08",
>         "kde-5.15-23.08",
>         "kde-6.2",
>         "kde-6.3",
>         "kde-6.4",
>         "kde-6.5",
>         "kde-6.6",
>         "kde-6.7",
>         "latest"
>     ]
> }
> ```
> 
> Thank you!

Yes, it takes approximately a week for the images to be rebuilt again unless i trigger it manually which i forgot to do last time
