### ISSUE TITLE
Do not error if the cache already exists

### ISSUE THREAD

**Issue by rkoesters** [flatpak/flatpak-github-actions#56]
If a build is able to successfully load a cache, then it will produce an error trying to save a cache with that same key. See the "Annotations" section in https://github.com/rkoesters/xkcd-gtk/actions/runs/1352160876 as an example.

The error is [ReserveCacheError](https://github.com/actions/toolkit/blob/master/packages/cache/src/cache.ts#L16) and it would be better to log an info message that says the cache already exists instead of an error message. Otherwise, anytime the cache is successfully used, errors are reported.

**Comment by bilelmoussaoui** [comment]
That's an upstream issue. We can't do much about it

**Comment by bilelmoussaoui** [comment]
The issue you're hitting is https://github.com/actions/toolkit/issues/658 and we can't do much about it actually

**Comment by bilelmoussaoui** [comment]
ideally such error wouldn't happen and the build would work just fine
