### ISSUE TITLE
Support runtimes and apps

### ISSUE THREAD

**Issue by ItsJamie9494** [flatpak/flatpak-github-actions#79]
When using this github action with an extension (which, as far as I know, creates `runtime/RDDN/arch/version` instead of `app/RDDN/arch/version`), the action fails. According to my logs, it fails because it cannot find `app/RDDN/arch/version`. Unfortunately, I can't seem to find an option to have it search for runtime instead of app.

I would like to see some sort of option to allow it to support runtime/extensions

**Comment by bilelmoussaoui** [comment]
It already supports runtimes just fine, elementary used to make use of it sometime iirc

**Comment by ItsJamie9494** [comment]
In my usage, it says it can't find the app.

**Comment by bilelmoussaoui** [comment]
Could you link to the manifest/your workflow file?

**Comment by ItsJamie9494** [comment]
https://github.com/tau-OS/github-actions/blob/main/.github/workflows/build-flatpak.yml

**Comment by Nalsai** [comment]
I'm having the same problem in the build-bundle part. Maybe there could be an option to skip building the bundle if you only want to upload the build to a repository.

**Comment by bilelmoussaoui** [comment]
Should be fixed with https://github.com/flatpak/flatpak-github-actions/pull/115
