### ISSUE TITLE
Tests should should modify flatpak manifest to pull the HEAD commit

### ISSUE THREAD

**Issue by andyholmes** [flatpak/flatpak-github-actions#86]
I noticed while working on #83 that (in the case of `git`, for example) `flatpak-builder` will build from the sources defined in the flatpak manifest. This isn't surprising, but it's almost certainly not what you want if your manifest points to your main branch and you are running tests on pull request.

I plan on taking a crack at this eventually, but if someone else wants to take it on before I do, feel free.

**Comment by bilelmoussaoui** [comment]
We already do that no? What is the flatpak manifest you are using? because we expect people to use a `type: dir` in their manifest instead of a `type: git`
