### ISSUE TITLE
appdata test fails due to missing ProxyResolver

### ISSUE THREAD

**Issue by CodedOre** [flatpak/flatpak-github-actions#87]
During my work on using Flatpak Builder in my project (see CodedOre/NewCaw#46), I ran into the problem that the appdata test fails as `appstream_util` fails to assert `Gio. ProxyResolver`:

```
(appstream-util:12): GLib-GIO-CRITICAL **: 10:28:50.002: g_proxy_resolver_lookup: assertion 'G_IS_PROXY_RESOLVER (resolver)' failed
```

I have also seen that the [CI builds of Dialect](https://github.com/dialect-app/dialect/runs/7393896149?check_suite_focus=true#step:4:305) also fail due to the exact same issue, so I assume the issue is with the Flatpak Builder action.

Used image: gnome-nightly

[Link to the failed build](https://github.com/CodedOre/NewCaw/runs/7407228778?check_suite_focus=true#step:5:556)
[The workflow file](https://github.com/CodedOre/NewCaw/blob/e0b304a2c7e324e63cced8d4533a077331805e4b/.github/workflows/flatpak.yml)

**Comment by mcatanzaro** [comment]
See: https://github.com/hughsie/appstream-glib/issues/449

**Comment by bilelmoussaoui** [comment]
Closing as unrelated to the action itself, thanks @mcatanzaro for the investigation!
