### ISSUE TITLE
Add git-lfs to dockerfile

### ISSUE THREAD

**Issue by 13hannes11** [flatpak/flatpak-github-actions#90]

**Comment by olof-nord** [comment]
Hello @13hannes11,
I am not involved in this project as a maintainer or developer, but as a user which keeps an eye on open issues out of curiosity.

You have not specified why you think git-lfs should be added to the Dockerfile.

Do you face a problem by the lack of this package? If so, what are your error logs, specifics about your issue?
What workarounds have you tried to address this problem yourself?

The more details you give, the more likely you are to get some feedback on this issue.

**Comment by bilelmoussaoui** [comment]
git-lfs is needed for flatpak-builder to run git-lfs init iirc

**Comment by 13hannes11** [comment]
The main reason is that I am storing Icons using  git-lfs so to be able to use this action i need git-lfs support.
