### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by GeorgesStavracas** [flatpak/flatpak-github-actions#94]
Since the big migration happened, seems like the Flatpak action is broken. See for example https://github.com/obsproject/obs-studio/actions/runs/3064364729/jobs/4947401540

GitHub Marketplace seems not to list the `v4` version of the action (see [here](https://github.com/marketplace/actions/flatpak-builder) and [here](https://github.com/flatpak/flatpak-github-actions/releases)).

**Comment by ntonnaett** [comment]
The container images didn't migrate yet. Could this be the problem?

**Comment by GeorgesStavracas** [comment]
Yes, we're slowly working on that

**Comment by rffontenelle** [comment]
I noticed successful "Flatpak Bundle" runs. Is it solved?

**Comment by bilelmoussaoui** [comment]
@GeorgesStavracas would you mind updating the issue with whatever is broken today? I totally the forgot the context here

**Comment by GeorgesStavracas** [comment]
I don't fully remember it too. Let's just close this, it's not useful.
